name: Dropbox-CSI
on: [push]
jobs:
  e2e:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: docker image build
        run: make image-build
      - name: install minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mkdir -p /usr/local/bin/
          sudo install minikube /usr/local/bin/
          sudo snap install kubectl --classic
      - name: test cluster up
        run: echo go #make test-cluster-up && kubectl get pods -A
      - name: create secret
        run: kubectl create secret generic dropbox-csi --from-literal=token=${{ secrets.DropboxToken }}
      - name: yaml deploy
        run: make yaml-deploy
      - name: e2e tests
        run: make test
  deliver:
    runs-on: ubuntu-20.04
    needs: e2e
    if: github.ref == 'refs/heads/master'
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: docker image build
        run: make image-build
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1        
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - 
        name: Build container image
        uses: docker/build-push-action@v2
        with: 
          context: artifacts
          repository: feelpp/dropbow-csi
          tags: ghcr.io/feelpp/dropbox-csi
          file: ./Dockerfile
          push: true
